"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getXataClient = exports.XataClient = void 0;
// Generated by Xata Codegen 0.29.2. Please do not edit.
const client_1 = require("@xata.io/client");
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "messages",
    columns: [
      { name: "sessionId", type: "string" },
      { name: "type", type: "string" },
      { name: "role", type: "string" },
      { name: "content", type: "text" },
      { name: "name", type: "string" },
      { name: "additionalKwargs", type: "text" },
    ],
  },
  {
    name: "responses",
    columns: [
      { name: "answer", type: "text" },
      { name: "input", type: "text" },
    ],
  },
  {
    name: "invocations",
    columns: [
      { name: "key", type: "text" },
      { name: "answer", type: "text" },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = (0, client_1.buildClient)();
const defaultOptions = {
  databaseURL:
    "https://Rishi-Raj-Jain-s-workspace-80514q.us-east-1.xata.sh/db/cache",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
exports.XataClient = XataClient;
let instance = undefined;
/** @type { () => XataClient } */
const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
exports.getXataClient = getXataClient;
